name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
          check-latest: true

      - name: Build
        run: |
          make sshvpn-linux-amd64
          chmod +x ./bin/sshvpn
          cp ./bin/sshvpn /usr/local/bin/sshvpn
          sshvpn version

      - name: Test
        run: go test -v -failfast ./... -timeout=60m

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
          check-latest: true

      - name: Build
        run: |
          make sshvpn-darwin-amd64
          chmod +x ./bin/sshvpn
          cp ./bin/sshvpn /usr/local/bin/sshvpn
          sshvpn version

      - name: Test
        run: go test -v -failfast ./... -timeout=60m

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build
        run: make sshvpn-windows-amd64